/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NuevaRouteImport } from './routes/nueva'
import { Route as MetricasRouteImport } from './routes/metricas'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as IndexRouteImport } from './routes/index'

const NuevaRoute = NuevaRouteImport.update({
  id: '/nueva',
  path: '/nueva',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricasRoute = MetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/calendario': typeof CalendarioRoute
  '/metricas': typeof MetricasRoute
  '/nueva': typeof NuevaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/calendario': typeof CalendarioRoute
  '/metricas': typeof MetricasRoute
  '/nueva': typeof NuevaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/calendario': typeof CalendarioRoute
  '/metricas': typeof MetricasRoute
  '/nueva': typeof NuevaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/biblioteca' | '/calendario' | '/metricas' | '/nueva'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/biblioteca' | '/calendario' | '/metricas' | '/nueva'
  id: '__root__' | '/' | '/biblioteca' | '/calendario' | '/metricas' | '/nueva'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliotecaRoute: typeof BibliotecaRoute
  CalendarioRoute: typeof CalendarioRoute
  MetricasRoute: typeof MetricasRoute
  NuevaRoute: typeof NuevaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nueva': {
      id: '/nueva'
      path: '/nueva'
      fullPath: '/nueva'
      preLoaderRoute: typeof NuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metricas': {
      id: '/metricas'
      path: '/metricas'
      fullPath: '/metricas'
      preLoaderRoute: typeof MetricasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliotecaRoute: BibliotecaRoute,
  CalendarioRoute: CalendarioRoute,
  MetricasRoute: MetricasRoute,
  NuevaRoute: NuevaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
