// Vercel serverless function wrapper around the Vite SSR bundle.
// Vite builds dist/server/server.js with a Cloudflare-Modules-style export
// `{ fetch(request, env, ctx) }`. We bridge it to the Web Fetch handler
// signature Vercel uses for Node functions.
// @ts-expect-error - dist/server/server.js is generated by `vite build` at deploy time
import server from "../dist/server/server.js";

export const config = { runtime: "nodejs" };

type SsrServer = { fetch: (r: Request, env: unknown, ctx: unknown) => Promise<Response> };

export default async function handler(req: Request): Promise<Response> {
  return (server as SsrServer).fetch(req, process.env, {});
}
